plugins {
    id 'java'
    id 'maven-publish'
    id 'com.enonic.xp.app'
    id 'com.enonic.defaults' version '2.1.7'
}

dependencies {
    implementation xplibs.api.core
    implementation xplibs.api.portal
    compileOnly xplibs.api.script

    include xplibs.portal
    include xplibs.context
    include xplibs.admin

    include "com.enonic.lib:lib-asset:2.0.0"

    include libs.lib.thymeleaf

    include 'com.google.auth:google-auth-library-oauth2-http:1.50.0'
}

repositories {
    mavenLocal()
    mavenCentral()
    xp.enonicRepo('dev')
    google()
}
